### ISSUE TITLE
add a piece of code.

### ISSUE THREAD

**Issue by grugnoymeme** [narstybits/MacOS-DuckyScripts#2]
hey i think u can add also `&& brew autoremove` to Homebrew Manager: Streamline Your macOS Package Updates.txt

**Comment by narstybits** [comment]
Great idea! I have made the addition to Homebrew Manager! Thank you for the
suggestion. If you ever have any other suggestions or questions, feel free
to give me a shout! Also give the repo a star if you haven't already this
will help spread the word about this exclusive Mac Repo!.

Thanks again!

**Comment by grugnoymeme** [comment]
i also have one. let's goo see and star mine as well ;)

**Comment by narstybits** [comment]
Heck yea what’s the name of your GitHub? I’ll go check it out!

**Comment by grugnoymeme** [comment]
just click on my name and see flipperzero-BadUSB repo

**Comment by narstybits** [comment]
This is awesome man. These scripts are tough! I need to add these to my
repo so people can find you through me and visa versa! I’m still pretty new
to GitHub but I see in other peoples repos they have other GitHub user’s
folders in their repo. How would I add some of your code to my repo so it
gives you the credit and links to your repo!?

**Comment by grugnoymeme** [comment]
it is called submodules, find it out on google is very simple

**Comment by narstybits** [comment]
Thanks, I'll check it out when I get home in about 8 hours. Also if you
don't mind checking out the API dropbox scripts i have. Still trying to
figure out a way to get it all into one package. Right now the process is
somewhat tedious ( you have to keep a separate command script on the
desktop). I would ideally just enter the api key and have the script
execute without having to read a seperate file from the desktop.

**Comment by narstybits** [comment]
Nice I got the submodule done. Git through the terminal is extra niceeee!

**Comment by narstybits** [comment]
definitely add me as a submodule when you get a chance. I know our time
differences are pretty large haha.
